language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t svwoodhouse/react-test -f ./client/Dockerfile.dev ././client/Dockerfile.dev

script:
  - docker run -e CI=true svwoodhouse/react-test npm test -- --coverage

after_success:
  - docker build -t svwoodhouse/multi-client ./client
  - docker build -t svwoodhouse/multi-nginx ./nginx
  - docker build -t svwoodhouse/multi-server ./server
  - docker build -t svwoodhouse/multi-worker ./worker

